!function(){if(!(!0===window.matchMedia("(prefers-reduced-motion: reduce)")||!0===window.matchMedia("(prefers-reduced-motion: reduce)").matches)){const p=document.createElement("div");let l=Math.random()*(window.innerWidth-32)+16,i=Math.random()*(window.innerHeight-32)+16,r=l,c=i,o=0,s=0,d=null,h=0;const f=10,n={idle:[[-3,-3]],alert:[[-7,-3]],scratchSelf:[[-5,0],[-6,0],[-7,0]],scratchWallN:[[0,0],[0,-1]],scratchWallS:[[-7,-1],[-6,-2]],scratchWallE:[[-2,-2],[-2,-3]],scratchWallW:[[-4,0],[-4,-1]],ear:[[-3,-3],[-7,-0]],tired:[[-3,-2]],sleeping:[[-2,0],[-2,-1]],N:[[-1,-2],[-1,-3]],NE:[[0,-2],[0,-3]],E:[[-3,0],[-3,-1]],SE:[[-5,-1],[-5,-2]],S:[[-6,-3],[-7,-2]],SW:[[-5,-3],[-6,-1]],W:[[-4,-2],[-4,-3]],NW:[[-1,0],[-1,-1]]};let e;const t=document.createElement("style");function a(t){p.isConnected&&(e=e||t,100<t-e&&(e=t,function(){o+=1;var t=l-r,e=i-c,a=Math.sqrt(t**2+e**2);var n;a<f||a<48?function(){if(s+=1,5<s&&0==Math.floor(100*Math.random())&&null==d){let t=["sleeping","scratchSelf"];l<64&&(t.push("scratchWallW"),t.push("scratchWallW")),i<64&&(t.push("scratchWallN"),t.push("scratchWallN")),l>window.innerWidth-64&&(t.push("scratchWallE"),t.push("scratchWallE")),i>window.innerHeight-64&&(t.push("scratchWallS"),t.push("scratchWallS")),d=t[Math.floor(Math.random()*t.length)]}switch(d){case"sleeping":if(h<16){m("ear",h);break}if(h<24){m("scratchSelf",h);break}if(h<32){m("tired",0);break}m("sleeping",Math.floor(h/4)),200<h&&u();break;case"scratchWallN":case"scratchWallS":case"scratchWallE":case"scratchWallW":case"scratchSelf":m(d,h),9<h&&u();break;default:return m("idle",0)}h+=1}():(d=null,h=0,1<s?(m("alert",0),s=Math.min(s,7),--s):(n=.5<e/a?"N":"",n+=e/a<-.5?"S":"",n+=.5<t/a?"W":"",m(n+=t/a<-.5?"E":"",o),l-=t/a*f,i-=e/a*f,l=Math.min(Math.max(32,l),window.innerWidth-32),i=Math.min(Math.max(32,i),window.innerHeight-32),p.style.left=l-16+"px",p.style.top=i-16+"px"))}()),window.requestAnimationFrame(a))}function m(t,e){t=n[t][e%n[t].length];p.style.backgroundPosition=`${32*t[0]}px ${32*t[1]}px`}function u(){d=null,h=0}t.innerHTML=`
            @keyframes heartBurst {
                0% { transform: scale(0); opacity: 0.6; }
                100% { transform: scale(1); opacity: 0; }
            }
            .heart {
                position: absolute;
                font-size: 2em;
                animation: heartBurst 1s ease-out;
                animation-fill-mode: forwards;
                color: #ab9df2;
                user-select: none;
            }
        `,document.head.appendChild(t),p.addEventListener("click",function(){const e=p.parentElement;var t=p.getBoundingClientRect(),a=window.scrollX||document.documentElement.scrollLeft,n=window.scrollY||document.documentElement.scrollTop,l=t.left+t.width/2+a,i=t.top+t.height/2+n;for(let t=0;t<10;t++){const o=document.createElement("div");o.className="heart",o.textContent="🌟";var r=50*(Math.random()-.5),c=50*(Math.random()-.5);o.style.left=l+r-16+"px",o.style.top=i+c-16+"px",o.style.transform=`translate(-50%, -50%) rotate(${360*Math.random()}deg)`,o.style.zIndex=2147483646,e.appendChild(o),setTimeout(()=>{e.removeChild(o)},1e3)}}),function(){p.id="oneko",p.ariaHidden=!0,p.style.width="32px",p.style.height="32px",p.style.position="fixed",p.style.pointerEvents="auto",p.style.imageRendering="pixelated",p.style.left=l-16+"px",p.style.top=i-16+"px",p.style.zIndex=2147483647,p.style.clipPath="inset(0 0 0 0)",p.style.transform="scale(2)";let t="https://cdn.jsdelivr.net/gh/Zhu-junwei/oneko.js@main/sakura.gif";var e=document.currentScript;e&&e.dataset.cat&&(t=e.dataset.cat),function(a,t){const n=document.createElement("canvas"),l=n.getContext("2d"),i=new Image;i.src=""+t,i.width=256,i.height=128,i.onload=function(){n.width=i.width,n.height=i.height,l.globalAlpha=.6,l.drawImage(i,0,0);var t=l.getImageData(0,0,n.width,n.height);const e=t.data;for(let t=0;t<e.length;t+=4)255==e[t]&&255==e[t+1]&&255==e[t+2]?(e[t]=237,e[t+1]=175,e[t+2]=31):(e[t]=e[t],e[t+1]=e[t+1]+123,e[t+2]=e[t+2]+255);l.putImageData(t,0,0),a.style.backgroundImage="url("+n.toDataURL()+")"}}(p,t),document.body.appendChild(p),document.addEventListener("mousemove",function(t){r=t.clientX,c=t.clientY}),window.requestAnimationFrame(a)}()}}();