const CLOCK_CONFIG={targetPage:"all",excludePaths:["null"],rectangle:"116.4074,39.9042",defaultRectangleEnabled:!1,defaultCity:"北京市",apiKeys:{weather:"11913b4e56b04955bba24466f2bdc455",map:"16273ca5eff5c6ebf263eb6e738576cb"}};function clockUpdateTime(e,c){let a="#000";switch(e.now.icon){case"100":a="#fdcc45";break;case"101":a="#fe6976";break;case"102":case"103":a="#fe7f5b";break;case"104":case"150":case"151":case"152":case"153":case"154":case"800":case"801":case"802":case"803":case"804":case"805":case"806":case"807":a="#2152d1";break;case"300":case"301":case"305":case"306":case"307":case"308":case"309":case"310":case"311":case"312":case"313":case"314":case"315":case"316":case"317":case"318":case"350":case"351":case"399":a="#49b1f5";break;case"302":case"303":case"304":a="#fdcc46";break;case"400":case"401":case"402":case"403":case"404":case"405":case"406":case"407":case"408":case"409":case"410":case"456":case"457":case"499":a="#a3c2dc";break;case"500":case"501":case"502":case"503":case"504":case"507":case"508":case"509":case"510":case"511":case"512":case"513":case"514":case"515":a="#97acba";break;case"900":case"999":a="red";break;case"901":a="#179fff;"}var t=document.getElementById("hexo_electric_clock");clock_box_html=`
  <div class="clock-row">
    <span id="card-clock-clockdate" class="card-clock-clockdate"></span>
    <span class="card-clock-weather"><i class="qi-${e.now.icon}-fill" style="color: ${a}"></i> ${e.now.text} <span>${e.now.temp}</span> ℃</span>
    <span class="card-clock-humidity">💧 ${e.now.humidity}%</span>
  </div>
  <div class="clock-row">
    <span id="card-clock-time" class="card-clock-time"></span>
  </div>
  <div class="clock-row">
    <span class="card-clock-windDir"> <i class="qi-gale"></i> ${e.now.windDir}</span>
    <span class="card-clock-location">${c}</span>
    <span id="card-clock-dackorlight" class="card-clock-dackorlight"></span>
  </div>
  `;var i=["SUN","MON","TUE","WED","THU","FRI","SAT"],c=document.getElementById("card-clock-loading");function s(){var e,c=new Date,a=n(c.getHours(),2)+":"+n(c.getMinutes(),2)+":"+n(c.getSeconds(),2),t=n(c.getFullYear(),4)+"-"+n(c.getMonth()+1,2)+"-"+n(c.getDate(),2)+" "+i[c.getDay()],s=c.getHours(),o=12<s?" P M":" A M";document.getElementById("card-clock-time")&&(e=document.getElementById("card-clock-time"),c=document.getElementById("card-clock-clockdate"),s=document.getElementById("card-clock-dackorlight"),e.innerHTML=a,c.innerHTML=t,s.innerHTML=o)}function n(e,c){for(var a="",t=0;t<c;t++)a+="0";return(a+e).slice(-c)}c&&(c.innerHTML=""),t.innerHTML=clock_box_html,setInterval(s,1e3),s()}class HexoElectricClock{constructor(e){this.config=e,this.clockElement=null}init(){if(this.shouldShow()){let e=document.createElement("link");e.rel="stylesheet",e.type="text/css",e.href="/js/widget/clock/clock.css",document.head.appendChild(e),this.inject(),this.getWeather()}}shouldShow(){const{targetPage:e,excludePaths:c}=this.config;return"all"!==e?location.pathname===e:!Array.isArray(c)||!c.some(e=>location.pathname.includes(e))}inject(){if(!document.getElementById("hexo_electric_clock")){const e=document.querySelector(".weather-clock");if(!e)return console.warn("未找到 .weather-clock");e.insertAdjacentHTML("afterbegin",`
            <div class="card-widget card-clock">
                <div class="card-glass">
                    <div class="card-background">
                        <div class="card-content">
                            <div id="hexo_electric_clock">
                                <div id="card-clock-loading" style="height:120px;display:flex;align-items:center;justify-content:center;color:#666">
                                    <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `)}}async fetchJSON(e){const c=await fetch(e);if(!c.ok)throw new Error("HTTP "+c.status);return c.json()}async getWeather(){var a,{defaultRectangleEnabled:t,rectangle:s,defaultCity:o,apiKeys:i}=this.config;if(!i.map||!i.weather)return this.update(null,o);try{let e,c;c=t&&s?(e=s,o):(a=await this.getLocationWithFallback(),e=a.location,a.city);var n=await this.fetchJSON(`https://devapi.qweather.com/v7/weather/now?location=${encodeURIComponent(e)}&key=`+i.weather);this.update(n,c)}catch(e){console.error("获取天气失败:",e),this.update(null,o)}}async getLocationWithFallback(){try{var e=await this.getBrowserLocation();return{location:e,city:await this.getCityByLocation(e)}}catch(e){console.warn("浏览器定位失败，降级到IP定位:",e.message)}try{return await this.getIPLocation()}catch(e){console.warn("IP定位失败，使用默认值:",e.message)}return{location:this.config.rectangle,city:this.config.defaultCity}}getBrowserLocation(){return new Promise((a,c)=>{if(!navigator.geolocation)return c(new Error("浏览器不支持 Geolocation API"));navigator.geolocation.getCurrentPosition(e=>{var{longitude:c,latitude:e}=e.coords;a(c+","+e)},e=>{c(new Error("Geolocation 错误: "+e.message))},{enableHighAccuracy:!1,timeout:5e3,maximumAge:6e4})})}async getIPLocation(){const e=await this.fetchJSON("https://restapi.amap.com/v3/ip?key="+this.config.apiKeys.map);var c=Array.isArray(e.rectangle)?this.config.rectangle:e.rectangle.split(";")[0];return{location:c,city:Array.isArray(e.rectangle)?this.config.defaultCity:await this.getCityByLocation(c)}}async getCityByLocation(e){e=await this.fetchJSON(`https://restapi.amap.com/v3/geocode/regeo?key=${this.config.apiKeys.map}&location=`+encodeURIComponent(e));if("1"!==e.status)return this.config.defaultCity;e=e.regeocode.addressComponent;return e?Array.isArray(e.city)?e.province||this.config.defaultCity:e.city||this.config.defaultCity:this.config.defaultCity}update(e,c){this.clockElement||(this.clockElement=document.getElementById("hexo_electric_clock")),this.clockElement&&"function"==typeof clockUpdateTime&&clockUpdateTime(e,c)}}const hexoClock=new HexoElectricClock(CLOCK_CONFIG);"loading"===document.readyState?document.addEventListener("DOMContentLoaded",()=>hexoClock.init()):hexoClock.init();